[tool.pdm]
name = "pdm"
version = {from = "pdm/__init__.py"}
description = "Python Development Master"
author = "frostming <mianghong@gmail.com>"
license = "MIT"
python_requires = ">=3.7"
readme = "README.md"

homepage = "https://github.com/pdm-project/pdm"
repository = "https://github.com/pdm-project/pdm"

keywords = ["packaging", "dependency", "workflow"]

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]


[tool.pdm.dependencies]
appdirs = "*"
click = "*"
distlib = "*"
pip = "<21.0.0,>=20.0.0"
pip_shims = "*"
pythonfinder = "*"
tomlkit = "*"
halo = "<1.0.0,>=0.0.28"


[tool.pdm.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
towncrier = "<20.0.0,>=19.2.0"
pytest-sugar = "<1.0.0,>=0.9.2"
pytest-xdist = "<2.0.0,>=1.31.0"

[tool.pdm.cli]
pdm = "pdm.cli.commands:cli"

[tool.intreehooks]
build-backend = "pdm.builders.api"

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
atomic = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true
known_first_party = "pdm"
known_third_party = "pip_shims"

[tool.black]
line-length = 88

[tool.towncrier]
package = "pdm"
filename = "CHANGELOG.md"
issue_format = "[#{issue}](https://github.com/frostming/pdm/issues/{issue})"
directory = "news/"
title_format = "Release v{version} ({project_date})"
template = "news/towncrier_template.md"
underlines = "-~^"

  [[tool.towncrier.type]]
  directory = "feature"
  name = "Features & Improvements"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "bugfix"
  name = "Bug Fixes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "doc"
  name = "Improved Documentation"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "dep"
  name = "Dependencies"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "removal"
  name = "Removals and Deprecations"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "misc"
  name = "Miscellany"
  showcontent = true

[build-system]
requires = ["intreehooks"]
build-backend = "intreehooks:loader"

